

// UTILS

export const INITIALIZE = 'INITIALIZE'
export const INITIALIZE_SUCCESS = 'INITIALIZE_SUCCESS'
export const INITIALIZE_FAILED = 'INITIALIZE_FAILED'

export const INITIALIZE_SERVER_REQUEST = 'INITIALIZE_SERVER_REQUEST'
export const INITIALIZE_SERVER_SUCCESS = 'INITIALIZE_REDUXAT_SERVER_SUCCESS'
export const INITIALIZE_SERVER_FAILURE = 'INITIALIZE_SERVER_FAILURE'

// PAGE

export const PAGE_CONTENT_REQUEST = 'PAGE_CONTENT_REQUEST'
export const PAGE_CONTENT_REQUEST_SUCCESS = 'PAGE_CONTENT_REQUEST_SUCCESS'
export const PAGE_CONTENT_REQUEST_FAILURE = 'PAGE_CONTENT_REQUEST_FAILURE'

// SEMINARS

export const SEMINARS_REQUEST = 'SEMINARS_REQUEST'
export const SEMINARS_REQUEST_SUCCESS = 'SEMINARS_REQUEST_SUCCESS'