

// UTILS

export const INITIALIZE = 'INITIALIZE'
export const INITIALIZE_SUCCESS = 'INITIALIZE_SUCCESS'
export const INITIALIZE_FAILED = 'INITIALIZE_FAILED'

// PAGE

export const PAGE_CONTENT_REQUEST = 'PAGE_CONTENT_REQUEST'
export const PAGE_CONTENT_REQUEST_SUCCESS = 'PAGE_CONTENT_REQUEST_SUCCESS'
export const PAGE_CONTENT_REQUEST_FAILURE = 'PAGE_CONTENT_REQUEST_FAILURE'